/* ============================================================
   רשימת הושבה — נבנתה מהאקסל של עמיתי (23.08.2026 14:13)
   פורמט: { name, table, zone }  ·  שולחנות חוזרים בין אזורים!
   ============================================================ */

const GUESTS = [
  { name: "עדי רוטנברג", table: "1", zone: "בחוץ" },
  { name: "עדי אופק", table: "1", zone: "בחוץ" },
  { name: "רעות אוחנה", table: "1", zone: "בחוץ" },
  { name: "אוריה שחרור", table: "1", zone: "בחוץ" },
  { name: "יעל קנר", table: "1", zone: "בחוץ" },
  { name: "קמה קדמון", table: "1", zone: "בחוץ" },
  { name: "רבקה מדמון", table: "1", zone: "בחוץ" },
  { name: "עדי רוז", table: "1", zone: "בחוץ" },
  { name: "רויה מאירי", table: "1", zone: "בחוץ" },
  { name: "רותם ברנשטיין", table: "1", zone: "בחוץ" },
  { name: "הדסה תייר", table: "2", zone: "בחוץ" },
  { name: "יעל הבר", table: "2", zone: "בחוץ" },
  { name: "הלל טסמה", table: "2", zone: "בחוץ" },
  { name: "רעות דנה", table: "2", zone: "בחוץ" },
  { name: "שירה פרחי", table: "2", zone: "בחוץ" },
  { name: "מורשה יוספסון", table: "2", zone: "בחוץ" },
  { name: "אוריה זילברמן", table: "2", zone: "בחוץ" },
  { name: "טל עמנואל", table: "2", zone: "בחוץ" },
  { name: "חנה רייך", table: "2", zone: "בחוץ" },
  { name: "עדי רמות", table: "2", zone: "בחוץ" },
  { name: "נעמה לוין", table: "2", zone: "בחוץ" },
  { name: "חרות אפשטיין", table: "2", zone: "בחוץ" },
  { name: "אלה צימר", table: "3", zone: "בחוץ" },
  { name: "שיר ארנון", table: "3", zone: "בחוץ" },
  { name: "ליאל בן לולו", table: "3", zone: "בחוץ" },
  { name: "שחר גוטפריד", table: "3", zone: "בחוץ" },
  { name: "שרה פוסט", table: "3", zone: "בחוץ" },
  { name: "מאיר אסף", table: "3", zone: "בחוץ" },
  { name: "ליאור קוסוי", table: "3", zone: "בחוץ" },
  { name: "גל בן יעקב", table: "3", zone: "בחוץ" },
  { name: "יובל בק", table: "3", zone: "בחוץ" },
  { name: "שיר בק", table: "3", zone: "בחוץ" },
  { name: "יונתן פנד", table: "4", zone: "בחוץ" },
  { name: "שיראל", table: "4", zone: "בחוץ" },
  { name: "עומר פנד", table: "4", zone: "בחוץ" },
  { name: "אריאל ואנונו", table: "4", zone: "בחוץ" },
  { name: "רועי רווח", table: "4", zone: "בחוץ" },
  { name: "עדי רווח", table: "4", zone: "בחוץ" },
  { name: "איתי רווח", table: "4", zone: "בחוץ" },
  { name: "נועם אבירם", table: "4", zone: "בחוץ" },
  { name: "שחר אבירם", table: "4", zone: "בחוץ" },
  { name: "אוראל ברון", table: "4", zone: "בחוץ" },
  { name: "אליה ברון", table: "4", zone: "בחוץ" },
  { name: "זיו אבירם", table: "4", zone: "בחוץ" },
  { name: "שני ואנונו", table: "5", zone: "בחוץ" },
  { name: "עלמה פנד", table: "5", zone: "בחוץ" },
  { name: "שירה אבירם", table: "5", zone: "בחוץ" },
  { name: "עופרי", table: "5", zone: "בחוץ" },
  { name: "יובל רווח", table: "5", zone: "בחוץ" },
  { name: "ישי שילה", table: "5", zone: "בחוץ" },
  { name: "חן שילה", table: "5", zone: "בחוץ" },
  { name: "הלל", table: "5", zone: "בחוץ" },
  { name: "בניה", table: "5", zone: "בחוץ" },
  { name: "תהל ואנונו", table: "5", zone: "בחוץ" },
  { name: "רוני ואנונו", table: "5", zone: "בחוץ" },
  { name: "תפארת סתר", table: "5", zone: "בחוץ" },
  { name: "אורי ואנונו", table: "1", zone: "במרפסת" },
  { name: "גוני ואנונו", table: "1", zone: "במרפסת" },
  { name: "שוש שלמון", table: "1", zone: "במרפסת" },
  { name: "עומרי שלמון", table: "1", zone: "במרפסת" },
  { name: "אליחי ואנונו", table: "1", zone: "במרפסת" },
  { name: "אביה ואנונו", table: "1", zone: "במרפסת" },
  { name: "שרה במברגר", table: "1", zone: "במרפסת" },
  { name: "אבי במברגר", table: "1", zone: "במרפסת" },
  { name: "דרור הוד", table: "1", zone: "במרפסת" },
  { name: "שגב", table: "1", zone: "במרפסת" },
  { name: "נריה ואנונו", table: "1", zone: "במרפסת" },
  { name: "עילי ואנונו", table: "1", zone: "במרפסת" },
  { name: "אסתי הרטוב", table: "2", zone: "במרפסת" },
  { name: "אפרת שינמן", table: "2", zone: "במרפסת" },
  { name: "הדסה ימיני", table: "2", zone: "במרפסת" },
  { name: "מיטל בנימין", table: "2", zone: "במרפסת" },
  { name: "הדר לוי", table: "2", zone: "במרפסת" },
  { name: "מוריה סולקיס", table: "2", zone: "במרפסת" },
  { name: "לירז אדלר", table: "2", zone: "במרפסת" },
  { name: "מיכל נחשון", table: "2", zone: "במרפסת" },
  { name: "נעמי הררי", table: "2", zone: "במרפסת" },
  { name: "צביה רכל", table: "2", zone: "במרפסת" },
  { name: "עידית חמו", table: "3", zone: "במרפסת" },
  { name: "אריאלה ברכה", table: "3", zone: "במרפסת" },
  { name: "אושרית פרידמן", table: "3", zone: "במרפסת" },
  { name: "תמי הורדן", table: "3", zone: "במרפסת" },
  { name: "טליה פיש", table: "3", zone: "במרפסת" },
  { name: "מילכה דרף", table: "3", zone: "במרפסת" },
  { name: "בני דרף", table: "3", zone: "במרפסת" },
  { name: "אפרת הנדל", table: "3", zone: "במרפסת" },
  { name: "נועם הנדל", table: "3", zone: "במרפסת" },
  { name: "כנרת שמואלי", table: "3", zone: "במרפסת" },
  { name: "יורם שמואלי", table: "3", zone: "במרפסת" },
  { name: "סבתא רותי", table: "1", zone: "בפנים" },
  { name: "מנחם קופל", table: "1", zone: "בפנים" },
  { name: "עמיחי קופל", table: "1", zone: "בפנים" },
  { name: "דודי קופל", table: "1", zone: "בפנים" },
  { name: "שפרה קופל", table: "1", zone: "בפנים" },
  { name: "אביעד קופל", table: "1", zone: "בפנים" },
  { name: "שמוליק שטרן", table: "1", zone: "בפנים" },
  { name: "שולה שטרן", table: "1", zone: "בפנים" },
  { name: "יאיר שטרן", table: "1", zone: "בפנים" },
  { name: "רינה בויאר", table: "1", zone: "בפנים" },
  { name: "מוטי פנד", table: "2", zone: "בפנים" },
  { name: "דורית פנד", table: "2", zone: "בפנים" },
  { name: "עירית רווח", table: "2", zone: "בפנים" },
  { name: "אלי רווח", table: "2", zone: "בפנים" },
  { name: "טלי אבירם", table: "2", zone: "בפנים" },
  { name: "ציון אבירם", table: "2", zone: "בפנים" },
  { name: "יעל שילה", table: "2", zone: "בפנים" },
  { name: "יניב שילה", table: "2", zone: "בפנים" },
  { name: "רחלי טאובר", table: "2", zone: "בפנים" },
  { name: "אליעזר טאובר", table: "2", zone: "בפנים" },
  { name: "ענת אביטן", table: "2", zone: "בפנים" },
  { name: "יניב אביטן", table: "2", zone: "בפנים" },
  { name: "משפחת אלי אואנונו", table: "3", zone: "בפנים" },
  { name: "רבקה ואנונו", table: "3", zone: "בפנים" },
  { name: "אוסנת ביטון", table: "3", zone: "בפנים" },
  { name: "סמדר סעדה", table: "4", zone: "בפנים" },
  { name: "איציק סעדה", table: "4", zone: "בפנים" },
  { name: "מור עיוכי", table: "4", zone: "בפנים" },
  { name: "דוד עיוכי", table: "4", zone: "בפנים" },
  { name: "הודיה דגו", table: "4", zone: "בפנים" },
  { name: "יונתן דגו", table: "4", zone: "בפנים" },
  { name: "דוד סעדה", table: "4", zone: "בפנים" },
  { name: "אביאל סעדה", table: "4", zone: "בפנים" },
  { name: "אביתר סעדה", table: "4", zone: "בפנים" },
  { name: "ספיר סעדה", table: "4", zone: "בפנים" },
  { name: "עפרה חורי", table: "5", zone: "בפנים" },
  { name: "שלמה חורי", table: "5", zone: "בפנים" },
  { name: "אוראל זוסמן", table: "5", zone: "בפנים" },
  { name: "אופיר זוסמן", table: "5", zone: "בפנים" },
  { name: "אליה חורי", table: "5", zone: "בפנים" },
  { name: "טליה חורי", table: "5", zone: "בפנים" },
  { name: "נורית", table: "5", zone: "בפנים" },
  { name: "לבנת סתר", table: "6", zone: "בפנים" },
  { name: "דודי סתר", table: "6", zone: "בפנים" },
  { name: "ידידיה סתר", table: "6", zone: "בפנים" },
  { name: "יאיר סתר", table: "6", zone: "בפנים" },
  { name: "אפרת שרביט", table: "6", zone: "בפנים" },
  { name: "יעקב שרביט", table: "6", zone: "בפנים" },
  { name: "נהוראי ואנונו", table: "6", zone: "בפנים" },
  { name: "שירה ואנונו", table: "6", zone: "בפנים" },
  { name: "נויה ואנונו", table: "6", zone: "בפנים" },
  { name: "אילה ואנונו", table: "6", zone: "בפנים" },
  { name: "נועה ואנונו", table: "6", zone: "בפנים" },
  { name: "סיגל דרשן", table: "7", zone: "בפנים" },
  { name: "שמי דרשן", table: "7", zone: "בפנים" },
  { name: "רונית כרמיאל", table: "7", zone: "בפנים" },
  { name: "יפה עמר", table: "7", zone: "בפנים" },
  { name: "רפאל עמר", table: "7", zone: "בפנים" },
  { name: "ריקי חנימוב", table: "7", zone: "בפנים" },
  { name: "אייל חנימוב", table: "7", zone: "בפנים" },
  { name: "אושרת שאצקי", table: "7", zone: "בפנים" },
  { name: "עינב בוקובזה", table: "7", zone: "בפנים" },
  { name: "מיכאל רוטנברג", table: "7", zone: "בפנים" },
  { name: "שרה רוטנברג", table: "7", zone: "בפנים" },
  { name: "רחלי גרין", table: "7", zone: "בפנים" },
  { name: "הרב מוטי שראל", table: "✦", zone: "השולחן של משגב ושהם" },
  { name: "הרב דוד מור יוסף", table: "✦", zone: "השולחן של משגב ושהם" },
  { name: "הרב אלי גרין", table: "✦", zone: "השולחן של משגב ושהם" },
  { name: "הרב רפאל טסמה", table: "✦", zone: "השולחן של משגב ושהם" },
];
