/* ============================================================
   רשימת הושבה סופית סופית — מהאקסל של עמיתי (25.08.2026)
   פורמט: { name, table, zone }  ·  שולחנות 1–24 ייחודיים
   ============================================================ */

const GUESTS = [
  { name: "אלון קיסר", table: "1", zone: "במרפסת" },
  { name: "רעות קיסר", table: "1", zone: "במרפסת" },
  { name: "דניאל קיסר", table: "1", zone: "במרפסת" },
  { name: "רחל קיסר", table: "1", zone: "במרפסת" },
  { name: "תמר קיסר", table: "1", zone: "במרפסת" },
  { name: "הללי", table: "1", zone: "במרפסת" },
  { name: "עיינה", table: "1", zone: "במרפסת" },
  { name: "אורי ואנונו", table: "2", zone: "במרפסת" },
  { name: "גוני ואנונו", table: "2", zone: "במרפסת" },
  { name: "שוש שלמון", table: "2", zone: "במרפסת" },
  { name: "עומרי שלמון", table: "2", zone: "במרפסת" },
  { name: "אליחי ואנונו", table: "2", zone: "במרפסת" },
  { name: "אביה ואנונו", table: "2", zone: "במרפסת" },
  { name: "שרה במברגר", table: "2", zone: "במרפסת" },
  { name: "אבי במברגר", table: "2", zone: "במרפסת" },
  { name: "נריה ואנונו", table: "2", zone: "במרפסת" },
  { name: "עילי ואנונו", table: "2", zone: "במרפסת" },
  { name: "דרור הוד", table: "2", zone: "במרפסת" },
  { name: "אסתי הרטוב", table: "3", zone: "במרפסת" },
  { name: "אפרת שינמן", table: "3", zone: "במרפסת" },
  { name: "הדסה ימיני", table: "3", zone: "במרפסת" },
  { name: "מיטל בנימין", table: "3", zone: "במרפסת" },
  { name: "הדר לוי", table: "3", zone: "במרפסת" },
  { name: "מוריה סולקיס", table: "3", zone: "במרפסת" },
  { name: "לירז אדלר", table: "3", zone: "במרפסת" },
  { name: "מיכל נחשון", table: "3", zone: "במרפסת" },
  { name: "נעמי הררי", table: "3", zone: "במרפסת" },
  { name: "צביה רכל", table: "3", zone: "במרפסת" },
  { name: "שלמה בן חיים", table: "4", zone: "במרפסת" },
  { name: "איילה בן חיים", table: "4", zone: "במרפסת" },
  { name: "אמיתי קיסר", table: "4", zone: "במרפסת" },
  { name: "שלום קיסר", table: "4", zone: "במרפסת" },
  { name: "אורית קיסר", table: "4", zone: "במרפסת" },
  { name: "אליאור בן חיים", table: "5", zone: "במרפסת" },
  { name: "מלי בן חיים", table: "5", zone: "במרפסת" },
  { name: "אורי בן חיים", table: "5", zone: "במרפסת" },
  { name: "אלון בן חיים", table: "5", zone: "במרפסת" },
  { name: "עוז קיסר", table: "5", zone: "במרפסת" },
  { name: "מור קיסר", table: "5", zone: "במרפסת" },
  { name: "איתן קיסר", table: "5", zone: "במרפסת" },
  { name: "גלי קיסר", table: "5", zone: "במרפסת" },
  { name: "עידית חמו", table: "6", zone: "במרפסת" },
  { name: "אריאלה ברכה", table: "6", zone: "במרפסת" },
  { name: "אושרית פרידמן", table: "6", zone: "במרפסת" },
  { name: "תמי הורדן", table: "6", zone: "במרפסת" },
  { name: "טליה פיש", table: "6", zone: "במרפסת" },
  { name: "מילכה דרף", table: "6", zone: "במרפסת" },
  { name: "בני דרף", table: "6", zone: "במרפסת" },
  { name: "אפרת הנדל", table: "6", zone: "במרפסת" },
  { name: "נועם הנדל", table: "6", zone: "במרפסת" },
  { name: "כנרת שמואלי", table: "6", zone: "במרפסת" },
  { name: "יורם שמואלי", table: "6", zone: "במרפסת" },
  { name: "סמדר סעדה", table: "7", zone: "בפנים" },
  { name: "איציק סעדה", table: "7", zone: "בפנים" },
  { name: "מור עיוכי", table: "7", zone: "בפנים" },
  { name: "דוד עיוכי", table: "7", zone: "בפנים" },
  { name: "הודיה דגו", table: "7", zone: "בפנים" },
  { name: "יונתן דגו", table: "7", zone: "בפנים" },
  { name: "דוד סעדה", table: "7", zone: "בפנים" },
  { name: "אביאל סעדה", table: "7", zone: "בפנים" },
  { name: "אביתר סעדה", table: "7", zone: "בפנים" },
  { name: "ספיר סעדה", table: "7", zone: "בפנים" },
  { name: "איתמר קיסר", table: "8", zone: "בפנים" },
  { name: "רלי קיסר", table: "8", zone: "בפנים" },
  { name: "מיקי יומטוביאן", table: "8", zone: "בפנים" },
  { name: "יובל קיסר", table: "8", zone: "בפנים" },
  { name: "מיכל קיסר", table: "8", zone: "בפנים" },
  { name: "יורם ואביגיל קלזן", table: "8", zone: "בפנים" },
  { name: "אביבה מסוארי", table: "8", zone: "בפנים" },
  { name: "ציון והב", table: "8", zone: "בפנים" },
  { name: "בתיה חוברה", table: "8", zone: "בפנים" },
  { name: "ארז דהרי ואביו", table: "9", zone: "בפנים" },
  { name: "אביתר כהן", table: "9", zone: "בפנים" },
  { name: "הרב רפאל טסמה", table: "9", zone: "בפנים" },
  { name: "אייל חנימוב", table: "9", zone: "בפנים" },
  { name: "הרב מוטי שראל", table: "9", zone: "בפנים" },
  { name: "הרב דוד מור יוסף", table: "9", zone: "בפנים" },
  { name: "מיכאל זביב", table: "9", zone: "בפנים" },
  { name: "נתנאל חן", table: "9", zone: "בפנים" },
  { name: "עדיאל וואנה", table: "9", zone: "בפנים" },
  { name: "אליהו הלוי", table: "9", zone: "בפנים" },
  { name: "אביתר מנצור", table: "9", zone: "בפנים" },
  { name: "סבתא רותי", table: "10", zone: "בפנים" },
  { name: "מנחם קופל", table: "10", zone: "בפנים" },
  { name: "עמיחי קופל", table: "10", zone: "בפנים" },
  { name: "דודי קופל", table: "10", zone: "בפנים" },
  { name: "שפרה קופל", table: "10", zone: "בפנים" },
  { name: "אביעד קופל", table: "10", zone: "בפנים" },
  { name: "שמוליק שטרן", table: "10", zone: "בפנים" },
  { name: "שולה שטרן", table: "10", zone: "בפנים" },
  { name: "יאיר שטרן", table: "10", zone: "בפנים" },
  { name: "רינה בויאר", table: "10", zone: "בפנים" },
  { name: "מוטי פנד", table: "11", zone: "בפנים" },
  { name: "דורית פנד", table: "11", zone: "בפנים" },
  { name: "עירית רווח", table: "11", zone: "בפנים" },
  { name: "אלי רווח", table: "11", zone: "בפנים" },
  { name: "טלי אבירם", table: "11", zone: "בפנים" },
  { name: "ציון אבירם", table: "11", zone: "בפנים" },
  { name: "יעל שילה", table: "11", zone: "בפנים" },
  { name: "יניב שילה", table: "11", zone: "בפנים" },
  { name: "רחלי טאובר", table: "11", zone: "בפנים" },
  { name: "אליעזר טאובר", table: "11", zone: "בפנים" },
  { name: "ענת אביטן", table: "11", zone: "בפנים" },
  { name: "יניב אביטן", table: "11", zone: "בפנים" },
  { name: "מיכאל רוטנברג", table: "12", zone: "בפנים" },
  { name: "שרה רוטנברג", table: "12", zone: "בפנים" },
  { name: "יפה עמר", table: "12", zone: "בפנים" },
  { name: "רפאל עמר", table: "12", zone: "בפנים" },
  { name: "יוסי סרי ורעיתו", table: "12", zone: "בפנים" },
  { name: "משולם גיספן", table: "12", zone: "בפנים" },
  { name: "עוזי מסוארי", table: "12", zone: "בפנים" },
  { name: "אליעזר ואפרת גלילי", table: "12", zone: "בפנים" },
  { name: "נעם חיים", table: "12", zone: "בפנים" },
  { name: "עפרה חורי", table: "13", zone: "בפנים" },
  { name: "שלמה חורי", table: "13", zone: "בפנים" },
  { name: "אוראל זוסמן", table: "13", zone: "בפנים" },
  { name: "אופיר זוסמן", table: "13", zone: "בפנים" },
  { name: "אליה חורי", table: "13", zone: "בפנים" },
  { name: "טליה חורי", table: "13", zone: "בפנים" },
  { name: "נורית", table: "13", zone: "בפנים" },
  { name: "סיגל דרשן", table: "14", zone: "בפנים" },
  { name: "רונית כרמיאל", table: "14", zone: "בפנים" },
  { name: "ריקי חנימוב", table: "14", zone: "בפנים" },
  { name: "אושרת שאצקי", table: "14", zone: "בפנים" },
  { name: "עינב בוקובזה", table: "14", zone: "בפנים" },
  { name: "רחלי גרין", table: "14", zone: "בפנים" },
  { name: "מירב זהבי", table: "14", zone: "בפנים" },
  { name: "לבנת סתר", table: "15", zone: "בפנים" },
  { name: "דודי סתר", table: "15", zone: "בפנים" },
  { name: "ידידיה סתר", table: "15", zone: "בפנים" },
  { name: "יאיר סתר", table: "15", zone: "בפנים" },
  { name: "אפרת שרביט", table: "15", zone: "בפנים" },
  { name: "יעקב שרביט", table: "15", zone: "בפנים" },
  { name: "נהוראי ואנונו", table: "15", zone: "בפנים" },
  { name: "שירה ואנונו", table: "15", zone: "בפנים" },
  { name: "נויה ואנונו", table: "15", zone: "בפנים" },
  { name: "אילה ואנונו", table: "15", zone: "בפנים" },
  { name: "נועה ואנונו", table: "15", zone: "בפנים" },
  { name: "משפחת אואנונו", table: "16", zone: "בפנים" },
  { name: "רבקה ואנונו", table: "16", zone: "בפנים" },
  { name: "אוסנת ביטון", table: "16", zone: "בפנים" },
  { name: "רועי דויטש", table: "17", zone: "בחוץ" },
  { name: "אוריה זהבי", table: "17", zone: "בחוץ" },
  { name: "אורי ברוך", table: "17", zone: "בחוץ" },
  { name: "דוד רוטנר ורעיתו", table: "17", zone: "בחוץ" },
  { name: "נעם מלמד ורעיתו", table: "17", zone: "בחוץ" },
  { name: "יעקב במברגר", table: "17", zone: "בחוץ" },
  { name: "אשר ויזל", table: "17", zone: "בחוץ" },
  { name: "אריאל ורעיתו", table: "17", zone: "בחוץ" },
  { name: "יהונתן פסל ורעיתו", table: "17", zone: "בחוץ" },
  { name: "אליה קופרמן", table: "17", zone: "בחוץ" },
  { name: "יהודה מאושר", table: "17", zone: "בחוץ" },
  { name: "הראל גרין", table: "17", zone: "בחוץ" },
  { name: "אליוט מיכאל", table: "18", zone: "בחוץ" },
  { name: "שרה אלל", table: "18", zone: "בחוץ" },
  { name: "אהוד ליאור", table: "18", zone: "בחוץ" },
  { name: "דביר זיכרי", table: "18", zone: "בחוץ" },
  { name: "הדס כהן", table: "18", zone: "בחוץ" },
  { name: "יונתן נוביצקי", table: "18", zone: "בחוץ" },
  { name: "נעה ריבלין", table: "18", zone: "בחוץ" },
  { name: "זיו קראוס", table: "18", zone: "בחוץ" },
  { name: "שני בחור", table: "18", zone: "בחוץ" },
  { name: "הדיה לינדנבאום", table: "18", zone: "בחוץ" },
  { name: "זוהר שמחון", table: "18", zone: "בחוץ" },
  { name: "אור לוי", table: "19", zone: "בחוץ" },
  { name: "איתמר נתן", table: "19", zone: "בחוץ" },
  { name: "דובי ליכטנשטיין", table: "19", zone: "בחוץ" },
  { name: "נתנאל סימן טוב", table: "19", zone: "בחוץ" },
  { name: "יצחק ירוחם", table: "19", zone: "בחוץ" },
  { name: "אלדור גמרסני", table: "19", zone: "בחוץ" },
  { name: "אופיר טוויטו", table: "19", zone: "בחוץ" },
  { name: "יהודה הריס", table: "19", zone: "בחוץ" },
  { name: "מאיר מלמד", table: "19", zone: "בחוץ" },
  { name: "שחר מולדובסקי", table: "19", zone: "בחוץ" },
  { name: "אביחי ביטון", table: "19", zone: "בחוץ" },
  { name: "עידן גרבי", table: "19", zone: "בחוץ" },
  { name: "הדסה תייר", table: "20", zone: "בחוץ" },
  { name: "יעל הבר", table: "20", zone: "בחוץ" },
  { name: "הלל טסמה", table: "20", zone: "בחוץ" },
  { name: "רעות דנה", table: "20", zone: "בחוץ" },
  { name: "שירה פרחי", table: "20", zone: "בחוץ" },
  { name: "מורשה יוספסון", table: "20", zone: "בחוץ" },
  { name: "אוריה זילברמן", table: "20", zone: "בחוץ" },
  { name: "טל עמנואל", table: "20", zone: "בחוץ" },
  { name: "חנה רייך", table: "20", zone: "בחוץ" },
  { name: "עדי רמות", table: "20", zone: "בחוץ" },
  { name: "נעמה לוין", table: "20", zone: "בחוץ" },
  { name: "חרות אפשטיין", table: "20", zone: "בחוץ" },
  { name: "עדי רוטנברג", table: "21", zone: "בחוץ" },
  { name: "עדי אופק", table: "21", zone: "בחוץ" },
  { name: "רעות אוחנה", table: "21", zone: "בחוץ" },
  { name: "אוריה שחרור", table: "21", zone: "בחוץ" },
  { name: "יעל קנר", table: "21", zone: "בחוץ" },
  { name: "קמה קדמון", table: "21", zone: "בחוץ" },
  { name: "רבקה מדמון", table: "21", zone: "בחוץ" },
  { name: "עדי רוז", table: "21", zone: "בחוץ" },
  { name: "רויה מאירי", table: "21", zone: "בחוץ" },
  { name: "רותם ברנשטיין", table: "21", zone: "בחוץ" },
  { name: "שני ואנונו", table: "22", zone: "בחוץ" },
  { name: "עלמה פנד", table: "22", zone: "בחוץ" },
  { name: "שירה אבירם", table: "22", zone: "בחוץ" },
  { name: "יובל רווח", table: "22", zone: "בחוץ" },
  { name: "ישי שילה", table: "22", zone: "בחוץ" },
  { name: "חן שילה", table: "22", zone: "בחוץ" },
  { name: "תהל ואנונו", table: "22", zone: "בחוץ" },
  { name: "רוני ואנונו", table: "22", zone: "בחוץ" },
  { name: "תפארת סתר", table: "22", zone: "בחוץ" },
  { name: "יונתן פנד", table: "23", zone: "בחוץ" },
  { name: "שיראל", table: "23", zone: "בחוץ" },
  { name: "עומר פנד", table: "23", zone: "בחוץ" },
  { name: "אריאל ואנונו", table: "23", zone: "בחוץ" },
  { name: "רועי רווח", table: "23", zone: "בחוץ" },
  { name: "עדי רווח", table: "23", zone: "בחוץ" },
  { name: "איתי רווח", table: "23", zone: "בחוץ" },
  { name: "נועם אבירם", table: "23", zone: "בחוץ" },
  { name: "שחר אבירם", table: "23", zone: "בחוץ" },
  { name: "אוראל ברון", table: "23", zone: "בחוץ" },
  { name: "אליה ברון", table: "23", zone: "בחוץ" },
  { name: "זיו אבירם", table: "23", zone: "בחוץ" },
  { name: "אורי קלור", table: "24", zone: "בחוץ" },
  { name: "שילה לוי", table: "24", zone: "בחוץ" },
  { name: "גל בן יעקב", table: "24", zone: "בחוץ" },
  { name: "יובל ושיר בק", table: "24", zone: "בחוץ" },
  { name: "מאיר אסף", table: "24", zone: "בחוץ" },
  { name: "שחר גוטפריד", table: "24", zone: "בחוץ" },
  { name: "שרה פוסט", table: "24", zone: "בחוץ" },
  { name: "ליאור קוסוי", table: "24", zone: "בחוץ" },
  { name: "שיר ארנון", table: "24", zone: "בחוץ" },
  { name: "אלה צימר", table: "24", zone: "בחוץ" },
  { name: "ליאל בן לולו", table: "24", zone: "בחוץ" },
  { name: "מעיין רזזנק", table: "24", zone: "בחוץ" },
];
